#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q |grep 'HDMI-A-0'; then
	bash ~/.screenlayout/bruh.sh
fi

bspc monitor HDMI-A-0 -d 1 2 3 4 5 
bspc monitor eDP -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          20
bspc config corner_radius       10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#border color
bspc config focused_border_color '#EBDBB2'
bspc config normal_border_color '#3C3836'i

#prelauched programs
picom --experimental-backend &
nitrogen --restore &
bash ~/.config/polybar/launch.sh &  
